# Generated by Django 3.0.4 on 2020-10-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Designation',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
